version: "3.0"
services: 
  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    container_name: "mydb"
    environment:
      SA_PASSWORD: "Teste1234"
      ACCEPT_EULA: "Y"
    ports: 
      - 1401:1433